### PR TITLE
Fix sin spacing

### PR DESCRIPTION
**Pull request by eluberoff**
cherry-picking https://github.com/mathquill/mathquill/pull/605 and https://github.com/mathquill/mathquill/pull/606

### CODE REVIEW

**Comment by ehberger** [comment]
@eluberoff @laughinghan Can someone either merge or close this PR?

**Comment by ehberger** [comment]
@eluberoff @jwales @laughinghan ping again on this.

**Comment by jwmerrill** [comment]
@eluberoff  d0ad996 is the commit that knox master is using, so deleting this branch without merging broke the build.

**Comment by jwmerrill** [comment]
I pushed up a new branch called `master-dcg-tmp` that has this commit so that the necessary commit is available again, but we need to sort out what's going on with our mathquill branches in a more permanent way.

**Comment by jwmerrill** [comment]
Going forward, let's standardize on `master-dcg` as our branch of record, and agree that we won't push updates to knox's submodule until commits are merged onto `master-dcg`.

However, I'm not totally sure what to do right now. Why did we decide to close this PR instead of merging it? Is it superseded by something else?

**Comment by eluberoff** [comment]
yikes, so sorry. I remembered it being on master-dcg so assumed we didn't
need this branch since that's been our policy. totally my fault.

**Comment by jwmerrill** [comment]
Ok, I'll just merge this into master-dcg then.

BTW, I don't intend to point the finger too harshly here. It's really a
systems issue. Submodules make it so easy to make mistakes like this, and
it'd be great if we could figure out more ways to make mistakes harder
instead of the default.

**Pull request closed without merging**
