### PR TITLE
Add typingPercentWritesPercentOf option.

### PR DESCRIPTION
**Pull request by jwmerrill**
TODO:
- [x] Find a way to allow this syntax to round trip through serializing and parsing
- [x] Tests

### CODE REVIEW

**Comment by jwmerrill** [comment]
Might be possible to do this by adding a `.finalizeTree` method to the `%` command. That seems to be how autoUnitalicize works--it's implemented as a `.finalizeTree` operation on `Letter` commands that looks at the letters siblings, and fuses them together if necessary.

**Comment by jwmerrill** [comment]
NOTE:

In 2d7c225 I had to add some special case parsing for the `%` symbol. Without this change to the parser, parsing `\%\operatorname{of}` and then asking for LaTeX produces `\%of` instead of `\%\operatorname{of}`.

Mathquill unfortunately doesn't do a great job of tracking which things were wrapped in `\operatorname` in expressions that it parses. Instead, it relies on the list of `autoOperatorNames` to do unitalicizing, and to resynthesize `\operatorname` during serialization.

An alternative here is to add `of` as an autoOperatorName, but I don't think we want to do that because I think there's too high a change that someone has written an implicit multipliclation of the variables `o` and `f` in the past, and I don't want to break graphs that did that.

One corner case here is that if someone pastes in an expression with a percent sign in it, and then tries to write `of` after the percent sign, it will stay `\%of` and won't be upgraded to `\%\operatorname{of}`. To get correct behavior in the calculator, they'll need to delete the `%` and type a new one to get the special `percentof` node. It's possible we could fix this by adding
siblingAdded behavior to the `%` node, but I'm not confident about doing the necessary surgery on the node tree. I think this will be uncommon enough in practice that we can get away with ignoring it.

**Comment by mikehaverstock** [comment]
How does something like this work with paste or cut? If you past a percent does that promote to % of? If you cut out the `%` does `of` get removed?

If not, then I think the long-term strategy for these kinds of configurations is to do this in the controllers. We get events for each separate key stroke and we decide how to carry out that action. We could very easily check for `%` and write `% of`.

But if this works even on paste and cut then that might be harder to do in the controller. But still not impossible.

**Comment by jwmerrill** [comment]
> If you past a percent does that promote to % of

No, pasting a `%` by itself doesn't have very good behavior here. You'll end up needed to delete it and type `%` again to end up with what you want.

> If you cut out the % does of get removed?

`%` of is selected/deleted as a unit, so I think you can't cut out just the `%`. For the same reason, you can't really get into the "copying only %" situation from the previous question unless you're pasting from some other environment.

> We get events for each separate key stroke and we decide how to carry out that action. We could very easily check for % and write % of.

That sounds pretty interesting.

**Pull request merged**
