### PR TITLE
update symbola-basic font

### PR DESCRIPTION
**Pull request by beth**
Adds a few glyphs to the symbola-basic font. Also, adds the unicode square to the basic-symbols square definition (for parity with other geometry symbols definitions). 

Process for font update: Used https://github.com/mathquill/subset-symbola (a branch with https://github.com/mathquill/subset-symbola/pull/3 and https://github.com/mathquill/subset-symbola/pull/2 combined) to generate 

* src/fonts/Symbola-basic.css
* src/fonts/Symbola-basic.ttf
* src/fonts/Symbola-basic.woff
* src/fonts/Symbola-basic.woff2
* src/fonts/Symbola-basic.eot

Related Knox PR: https://github.com/desmosinc/knox/pull/16981

### CODE REVIEW

**Review by Abee007 — APPROVED** [review]
LGTM!

**Comment by beth** [comment]
@jwmerrill You tried to warn us about needing to update Symbola when adding basic symbols! Many apologies for not appropriately heeding your warning 😅

**Comment by jwmerrill** [comment]
> Process:
> A designer on the Amplify side copied glyphs from the full Symbola font into Symbola-basic, and then exported the file formats that were included in the repo.

In the past, we have used this project to generate our Symbola subset: https://github.com/mathquill/subset-symbola/

Could we try using that process? It'd be nice to keep it more automated unless there's some reason we can't.

**Comment by beth** [comment]
@jwmerrill Thank you! We will use that - two questions though - 
1. Is there a record of which symbols were used to generate the current Symbola-basic in the desmosinc fork?
2. Where would we update this record after we add some symbols?

**Comment by jwmerrill** [comment]
The symbols are specified [in the Makefile](https://github.com/mathquill/subset-symbola/blob/ee1c18ca6a41ab51236581c226f57229328474a7/Makefile#L16-L17).

You can either specify them as text by adding more entries to the `--text` string, or by their numerical code points, using the `--unicodes` flag. I recommend using the text version for things that look like normal glyphs. The `--unicodes` part is currently used for [Combining Macron Below](https://www.unicodepedia.com/unicode/combining-diacritical-marks/331/combining-macron-below/) that is confusing and hard to edit when it appears in the `--text` string with other characters.

Suggested process
1. Update the Makefile
2. Run a build, and copy the font wherever you need to to verify that it's working the way you need it to.
3. Make a PR with your changes into https://github.com/mathquill/subset-symbola
4. Also make a PR into this repo that checks in the built result that you want

You can assign me to review both PRs.

**Comment by beth** [comment]
@jwmerrill Okay, thank you! We saw the symbols in the makefile but since it was in the mathquill org rather than desmosinc org, we were leery of editing/thought there might have been a different source of truth. :) Will do!

**Comment by jwmerrill** [comment]
I'm the only commiter to https://github.com/mathquill/subset-symbola/ so far. Please join the club!

**Review by jwmerrill — APPROVED** [review]

**Pull request merged**
