### PR TITLE
Fix injection vulnerability

### PR DESCRIPTION
**Pull request by laughinghan**
https://github.com/desmosinc/pillow/issues/7249
https://github.com/desmosinc/knox/issues/6833

### CODE REVIEW

**Comment by eluberoff** [comment]
Awesome. I'll get to this tonight! At dinner now. Thanks x1000, han.

**Comment by eluberoff** [comment]
Awesome. Merge away! And then put up a PR into knox that just bumps
mathquill?

**Comment by laughinghan** [comment]
Would you mind doing that?

Han

**Comment by sclower** [comment]
I will take care of it.

**Pull request merged**
